"""Added soil data fields to Location model

Revision ID: 541c58e66640
Revises: 86493ad2f95c
Create Date: 2025-01-15 14:35:10.173428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541c58e66640'
down_revision = '86493ad2f95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('sand', sa.Float(), nullable=True),
    sa.Column('clay', sa.Float(), nullable=True),
    sa.Column('silt', sa.Float(), nullable=True),
    sa.Column('ocd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('location')
    # ### end Alembic commands ###
