"""updated state saving functions

Revision ID: eb756069b9bd
Revises: 541c58e66640
Create Date: 2025-01-17 13:37:38.191467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb756069b9bd'
down_revision = '541c58e66640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farm_data')
    op.drop_table('recommendation')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('state')

    op.create_table('recommendation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('farm_id', sa.INTEGER(), nullable=False),
    sa.Column('weather_summary', sa.VARCHAR(length=500), nullable=False),
    sa.Column('final_suggestion', sa.VARCHAR(length=300), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('soil_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('crop_preferences', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
